#!/bin/bash

DIR="Projetos"
OUTPUT="projetos.json"
URL="https://raw.githubusercontent.com/LinuxDicasPro/LinuxDicasPro_Public_Files/refs/heads/master"

echo "[" > "$OUTPUT"

first=true

find "$DIR" -type f -name "*.md" | while read -r file; do
    title=$(grep -m1 '^#' "$file" | sed 's/^# *//; s/"/\\"/g')
    subtitle=$(grep -m1 '^##' "$file" | sed 's/^## *//; s/"/\\"/g')

    dir=$(dirname "$file")
    banner_path="$dir/banner.webp"
    if [ ! -f "$banner_path" ]; then
        banner_path=null
    else
        banner_path="$banner_path"
    fi

    if [ "$first" = true ]; then
        first=false
    else
        echo "," >> "$OUTPUT"
    fi

    echo -e \
"    {
        \"title\": \"$title\",
        \"subtitle\": \"$subtitle\",
        \"link\": \"$URL/$file\",
        \"banner\":\"$URL/$banner_path\"
    }" >> "$OUTPUT"
done

# Fecha o JSON
echo "]" >> "$OUTPUT"

echo "Arquivo $OUTPUT gerado com sucesso!"
